# Generated by Django 3.2.25 on 2025-07-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jamb_Result', models.FileField(upload_to='media/jamb_result')),
            ],
            options={
                'verbose_name_plural': 'JAMB Result Upload',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='select', max_length=150)),
                ('first_Name', models.CharField(default='select', max_length=150)),
                ('other_Name', models.CharField(default='select', max_length=150)),
                ('email', models.EmailField(default='example@example.com', max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('reg_No', models.CharField(default='23u764', max_length=20, unique=True)),
                ('phone', models.CharField(default='234', max_length=25, unique=True)),
                ('fee_status', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(blank=True, default='avatar', upload_to='profile_pic/Student/')),
                ('home_Address', models.CharField(max_length=40)),
                ('mother_Maiden_name', models.CharField(max_length=200)),
                ('matrix_No', models.CharField(default='2003/csc-0001', max_length=20)),
                ('admission_status', models.BooleanField(default=False)),
                ('start_class', models.DateField(auto_now_add=True)),
                ('semester', models.IntegerField(default=1)),
                ('academic_session', models.CharField(default='2022/2023', max_length=20)),
                ('programme_duration', models.IntegerField(default=4)),
                ('graduation_year', models.IntegerField(default=2026)),
                ('admitted_Department', models.ForeignKey(default='Computer Science', on_delete=django.db.models.deletion.CASCADE, to='admission.department')),
                ('admitted_programme', models.ForeignKey(default='Not Admitted', on_delete=django.db.models.deletion.CASCADE, to='admission.programme')),
                ('local_Government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.lga')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.nationality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.state')),
                ('village_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.village')),
            ],
            options={
                'verbose_name_plural': 'Students Personal Information',
            },
        ),
        migrations.CreateModel(
            name='Applicant_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='select', max_length=150)),
                ('first_Name', models.CharField(default='select', max_length=150)),
                ('other_Name', models.CharField(default='select', max_length=150)),
                ('email', models.EmailField(default='example@example.com', max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('reg_No', models.CharField(default='23u764', max_length=20, unique=True)),
                ('phone', models.CharField(default='234', max_length=25, unique=True)),
                ('choice_One', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admission.choiceone', unique=True)),
                ('choice_Three', models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='admission.choicethree', unique=True)),
                ('choice_Two', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='admission.choicetwo', unique=True)),
                ('lga_Origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.lga')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.country')),
                ('state_Origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.state')),
            ],
            options={
                'verbose_name_plural': 'Candidate Application',
            },
        ),
    ]
