# Generated by Django 3.2.25 on 2025-07-24 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_db',
            name='descriptionA',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question_db',
            name='descriptionB',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question_db',
            name='descriptionC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question_db',
            name='descriptionD',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 22, 54, 0, 679675)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 22, 54, 0, 679656)),
        ),
    ]
