# Generated by Django 3.2.25 on 2025-07-24 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('questions', '0003_auto_20250724_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_paper',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='course.course'),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 0, 23, 21, 655370)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 0, 23, 21, 655352)),
        ),
    ]
